name: workflow
     
# Le workflow s'exécute lorsqu'un push est effectué sur la branche develop
on:
  push:
    branches:
      - develop  # Ajout d'un espace après le tiret pour la syntaxe correcte

jobs:
  lint:
    runs-on: self-hosted

    steps:
      # Étape 1 : Checker le code du dépôt, re-cloner le repository
      - name: Check du repository
        uses: actions/checkout@v3

      # Étape 2 : Trouver les fichiers PHP et exécuter "php -l" sur eux
      - name: Execution sur les fichiers PHP
        run: find . -iname "*.php" -exec php -l {} \;


